version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:373

    python3-agent:
        build:
            context: python3
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./python3:/app
