version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:384

    python3-agent:
        build:
            context: python3
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.dev
        volumes:
            - ./python3:/app
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 1024m

    python3-vm-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.vm.dev
        volumes:
            - ./python3:/app
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 1024m

    python3-finals-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.finals.dev
        volumes:
            - ./python3:/app
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 1024m

    python3-agro-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile.finals.dev
        volumes:
            - ./python3:/app
        deploy:
            resources:
                limits:
                    cpus: 2
                    memory: 1024m
